### ISSUE TITLE
this.matchMapBlue.split is not a function

### ISSUE THREAD

**Issue by LxGunnar** [ebshimizu/soothsayer#34]
Falindrith had a problem opening soothsayer and I have no idea what it could be XD
Do you know what it can be?
![image](https://user-images.githubusercontent.com/39277473/190818002-7e43c703-e37f-454e-a2d1-002b5c1ad3e5.png)

**Comment by Tots-Snaps** [comment]
hello there 👋

I have the same Issue but can't find the way to resolved It ... any clues ? =)
